### ISSUE TITLE
sorry. i have some questions on your other program called ios-analyisi

### ISSUE THREAD

**Issue by MinghaoLin2000** [Churro/avr-aes128-groestl256#1]
i'm sorry to disturb you. -.-,  i can't use your tool to analysis my ios application.  after i compiled whole project, i run the extract.sh and run.sh to try to analysis my problem. there are something wrong happened.  
"####################################################
Bins/breakmedaddy
####################################################
64-bit binary not found -> extract
ERROR: can't extract binary"

i want to ask if i do something wrong.   i used extrach.sh to extract binary of ipa. and  i use this binary as parm for the run.sh to get result.  hope u can help me .thx

**Comment by Churro** [comment]
Hi, make sure you have the [lipo](https://www.unix.com/man-page/osx/1/lipo/) tool installed. Otherwise, run the commands from `run.sh` manually to see what's the issue.

**Comment by MinghaoLin2000** [comment]
> Hi, make sure you have the [lipo](https://www.unix.com/man-page/osx/1/lipo/) tool installed. Otherwise, run the commands from `run.sh` manually to see what's the issue.

could you give me your email address?  i hope that i can communicate with you. I'll try the solution you mentioned. thx

**Comment by Churro** [comment]
Sorry but I currrently don't provide active support for the [ios-analysis](https://github.com/Churro/ios-analysis) project.

**Comment by MinghaoLin2000** [comment]
> Sorry but I currrently don't provide active support for the [ios-analysis](https://github.com/Churro/ios-analysis) project.

oh. i got it.  thanks for your answer!
